export type ProduceType = "Vegetable" | "Fruit";

export type ProduceSeed = {
  key: string;
  query: string;
  type: ProduceType;
  price: string;
  stock: string;
  imageKey?: string;
  featured?: boolean;
};

export type ProduceItem = ProduceSeed & {
  name: string;
  image: string;
};

export const produceSeeds: ProduceSeed[] = [
  { key: "tomato", query: "tomato", type: "Vegetable", price: "Rs 28/kg", stock: "3.4 t available", featured: true },
  { key: "carrot", query: "carrot", type: "Vegetable", price: "Rs 32/kg", stock: "2.1 t available", featured: true },
  { key: "spinach", query: "spinach", type: "Vegetable", price: "Rs 18/bunch", stock: "860 bunches", featured: true },
  { key: "bell-pepper", query: "bell pepper", type: "Vegetable", price: "Rs 44/kg", stock: "1.7 t available", featured: true },
  { key: "cauliflower", query: "cauliflower", type: "Vegetable", price: "Rs 38/kg", stock: "1.4 t available" },
  { key: "broccoli", query: "broccoli", type: "Vegetable", price: "Rs 58/kg", stock: "920 kg available" },
  { key: "cabbage", query: "cabbage", type: "Vegetable", price: "Rs 24/kg", stock: "2.8 t available" },
  { key: "cucumber", query: "cucumber", type: "Vegetable", price: "Rs 26/kg", stock: "1.9 t available" },
  { key: "eggplant", query: "eggplant", type: "Vegetable", price: "Rs 34/kg", stock: "1.1 t available" },
  { key: "okra", query: "okra", type: "Vegetable", price: "Rs 42/kg", stock: "760 kg available" },
  { key: "potato", query: "potato", type: "Vegetable", price: "Rs 18/kg", stock: "6.1 t available" },
  { key: "onion", query: "onion", type: "Vegetable", price: "Rs 22/kg", stock: "5.8 t available" },
  { key: "beetroot", query: "beetroot", type: "Vegetable", price: "Rs 36/kg", stock: "880 kg available" },
  { key: "radish", query: "radish", type: "Vegetable", price: "Rs 20/kg", stock: "710 kg available" },
  { key: "pumpkin", query: "pumpkin", type: "Vegetable", price: "Rs 30/kg", stock: "2.3 t available" },
  { key: "bitter-gourd", query: "bitter gourd", type: "Vegetable", price: "Rs 48/kg", stock: "640 kg available" },
  { key: "bottle-gourd", query: "bottle gourd", type: "Vegetable", price: "Rs 28/kg", stock: "1.2 t available" },
  { key: "green-peas", query: "green peas", type: "Vegetable", price: "Rs 72/kg", stock: "530 kg available" },
  { key: "sweet-corn", query: "sweet corn", type: "Vegetable", price: "Rs 35/piece", stock: "1,800 pieces" },
  { key: "mushroom", query: "button mushroom", type: "Vegetable", price: "Rs 95/kg", stock: "420 kg available" },
  { key: "garlic", query: "garlic", type: "Vegetable", price: "Rs 140/kg", stock: "650 kg available" },
  { key: "ginger", query: "ginger", type: "Vegetable", price: "Rs 110/kg", stock: "580 kg available" },
  { key: "green-chilli", query: "green chilli", type: "Vegetable", price: "Rs 62/kg", stock: "360 kg available" },
  { key: "lettuce", query: "lettuce", type: "Vegetable", price: "Rs 55/head", stock: "900 heads" },

  { key: "apple", query: "apple", type: "Fruit", price: "Rs 120/kg", stock: "1.8 t available", featured: true },
  { key: "banana", query: "banana", type: "Fruit", price: "Rs 46/dozen", stock: "3,200 dozen", featured: true },
  { key: "mango", query: "mango", type: "Fruit", price: "Rs 90/kg", stock: "2.6 t available", featured: true },
  { key: "grapes", query: "grapes", type: "Fruit", price: "Rs 76/kg", stock: "1.2 t available", featured: true },
  { key: "orange", query: "orange", type: "Fruit", price: "Rs 68/kg", stock: "2.4 t available" },
  { key: "papaya", query: "papaya", type: "Fruit", price: "Rs 42/kg", stock: "1.5 t available" },
  { key: "pineapple", query: "pineapple", type: "Fruit", price: "Rs 70/piece", stock: "1,100 pieces" },
  { key: "watermelon", query: "watermelon", type: "Fruit", price: "Rs 24/kg", stock: "4.3 t available" },
  { key: "strawberry", query: "strawberry", type: "Fruit", price: "Rs 180/box", stock: "620 boxes" },
  { key: "pomegranate", query: "pomegranate", type: "Fruit", price: "Rs 135/kg", stock: "980 kg available" },
  { key: "kiwi", query: "kiwi", type: "Fruit", price: "Rs 32/piece", stock: "1,450 pieces" },
  { key: "pear", query: "pear", type: "Fruit", price: "Rs 115/kg", stock: "860 kg available" },
  { key: "guava", query: "guava", type: "Fruit", price: "Rs 58/kg", stock: "1.1 t available" },
  { key: "sapota", query: "sapodilla", type: "Fruit", price: "Rs 72/kg", stock: "760 kg available" },
  { key: "custard-apple", query: "custard apple", type: "Fruit", price: "Rs 95/kg", stock: "520 kg available" },
  { key: "dragon-fruit", query: "dragon fruit", type: "Fruit", price: "Rs 145/kg", stock: "430 kg available" },
  { key: "lychee", query: "lychee", type: "Fruit", price: "Rs 160/kg", stock: "390 kg available" },
  { key: "peach", query: "peach", type: "Fruit", price: "Rs 130/kg", stock: "610 kg available" },
  { key: "plum", query: "plum", type: "Fruit", price: "Rs 125/kg", stock: "540 kg available" },
  { key: "coconut", query: "coconut", type: "Fruit", price: "Rs 38/piece", stock: "2,400 pieces" },

  { key: "cherry-tomato", query: "cherry tomato", type: "Vegetable", price: "Rs 64/kg", stock: "720 kg available", imageKey: "tomato" },
  { key: "roma-tomato", query: "roma tomato", type: "Vegetable", price: "Rs 38/kg", stock: "1.3 t available", imageKey: "tomato" },
  { key: "grape-tomato", query: "grape tomato", type: "Vegetable", price: "Rs 70/kg", stock: "460 kg available", imageKey: "tomato" },
  { key: "green-tomato", query: "green tomato", type: "Vegetable", price: "Rs 42/kg", stock: "610 kg available", imageKey: "tomato" },
  { key: "baby-carrot", query: "baby carrot", type: "Vegetable", price: "Rs 58/kg", stock: "540 kg available", imageKey: "carrot" },
  { key: "red-carrot", query: "red carrot", type: "Vegetable", price: "Rs 36/kg", stock: "1.2 t available", imageKey: "carrot" },
  { key: "black-carrot", query: "black carrot", type: "Vegetable", price: "Rs 52/kg", stock: "430 kg available", imageKey: "carrot" },
  { key: "carrot-bunch", query: "carrot bunch", type: "Vegetable", price: "Rs 48/bunch", stock: "1,100 bunches", imageKey: "carrot" },
  { key: "baby-spinach", query: "baby spinach", type: "Vegetable", price: "Rs 42/bunch", stock: "680 bunches", imageKey: "spinach" },
  { key: "malabar-spinach", query: "malabar spinach", type: "Vegetable", price: "Rs 34/bunch", stock: "520 bunches", imageKey: "spinach" },
  { key: "water-spinach", query: "water spinach", type: "Vegetable", price: "Rs 30/bunch", stock: "610 bunches", imageKey: "spinach" },
  { key: "amaranth-leaves", query: "amaranth leaves", type: "Vegetable", price: "Rs 24/bunch", stock: "840 bunches", imageKey: "spinach" },
  { key: "red-capsicum", query: "red capsicum", type: "Vegetable", price: "Rs 86/kg", stock: "480 kg available", imageKey: "bell-pepper" },
  { key: "yellow-capsicum", query: "yellow capsicum", type: "Vegetable", price: "Rs 82/kg", stock: "450 kg available", imageKey: "bell-pepper" },
  { key: "green-capsicum", query: "green capsicum", type: "Vegetable", price: "Rs 48/kg", stock: "1 t available", imageKey: "bell-pepper" },
  { key: "mini-bell-pepper", query: "mini bell pepper", type: "Vegetable", price: "Rs 95/kg", stock: "360 kg available", imageKey: "bell-pepper" },
  { key: "purple-cabbage", query: "purple cabbage", type: "Vegetable", price: "Rs 52/kg", stock: "720 kg available", imageKey: "cabbage" },
  { key: "napa-cabbage", query: "napa cabbage", type: "Vegetable", price: "Rs 56/kg", stock: "530 kg available", imageKey: "cabbage" },
  { key: "savoy-cabbage", query: "savoy cabbage", type: "Vegetable", price: "Rs 60/kg", stock: "420 kg available", imageKey: "cabbage" },
  { key: "bok-choy", query: "bok choy", type: "Vegetable", price: "Rs 64/kg", stock: "510 kg available", imageKey: "cabbage" },
  { key: "english-cucumber", query: "english cucumber", type: "Vegetable", price: "Rs 38/kg", stock: "970 kg available", imageKey: "cucumber" },
  { key: "persian-cucumber", query: "persian cucumber", type: "Vegetable", price: "Rs 46/kg", stock: "630 kg available", imageKey: "cucumber" },
  { key: "baby-cucumber", query: "baby cucumber", type: "Vegetable", price: "Rs 54/kg", stock: "580 kg available", imageKey: "cucumber" },
  { key: "pickling-cucumber", query: "pickling cucumber", type: "Vegetable", price: "Rs 40/kg", stock: "760 kg available", imageKey: "cucumber" },
  { key: "white-onion", query: "white onion", type: "Vegetable", price: "Rs 28/kg", stock: "2.7 t available", imageKey: "onion" },
  { key: "red-onion", query: "red onion", type: "Vegetable", price: "Rs 26/kg", stock: "3.1 t available", imageKey: "onion" },
  { key: "spring-onion", query: "spring onion", type: "Vegetable", price: "Rs 22/bunch", stock: "1,400 bunches", imageKey: "onion" },
  { key: "pearl-onion", query: "pearl onion", type: "Vegetable", price: "Rs 62/kg", stock: "690 kg available", imageKey: "onion" },
  { key: "baby-potato", query: "baby potato", type: "Vegetable", price: "Rs 34/kg", stock: "1.8 t available", imageKey: "potato" },
  { key: "red-potato", query: "red potato", type: "Vegetable", price: "Rs 32/kg", stock: "1.5 t available", imageKey: "potato" },
  { key: "white-potato", query: "white potato", type: "Vegetable", price: "Rs 24/kg", stock: "2.9 t available", imageKey: "potato" },
  { key: "new-potato", query: "new potato", type: "Vegetable", price: "Rs 30/kg", stock: "1.4 t available", imageKey: "potato" },
  { key: "purple-potato", query: "purple potato", type: "Vegetable", price: "Rs 68/kg", stock: "420 kg available", imageKey: "potato" },
  { key: "baby-cauliflower", query: "baby cauliflower", type: "Vegetable", price: "Rs 54/kg", stock: "440 kg available", imageKey: "cauliflower" },
  { key: "purple-cauliflower", query: "purple cauliflower", type: "Vegetable", price: "Rs 76/kg", stock: "320 kg available", imageKey: "cauliflower" },
  { key: "romanesco", query: "romanesco", type: "Vegetable", price: "Rs 95/kg", stock: "260 kg available", imageKey: "cauliflower" },
  { key: "broccolini", query: "broccolini", type: "Vegetable", price: "Rs 110/kg", stock: "290 kg available", imageKey: "broccoli" },
  { key: "broccoli-rabe", query: "broccoli rabe", type: "Vegetable", price: "Rs 88/kg", stock: "310 kg available", imageKey: "broccoli" },
  { key: "baby-broccoli", query: "baby broccoli", type: "Vegetable", price: "Rs 92/kg", stock: "360 kg available", imageKey: "broccoli" },
  { key: "long-eggplant", query: "long eggplant", type: "Vegetable", price: "Rs 42/kg", stock: "760 kg available", imageKey: "eggplant" },
  { key: "round-eggplant", query: "round eggplant", type: "Vegetable", price: "Rs 44/kg", stock: "650 kg available", imageKey: "eggplant" },
  { key: "green-eggplant", query: "green eggplant", type: "Vegetable", price: "Rs 48/kg", stock: "520 kg available", imageKey: "eggplant" },
  { key: "baby-okra", query: "baby okra", type: "Vegetable", price: "Rs 58/kg", stock: "480 kg available", imageKey: "okra" },
  { key: "tender-okra", query: "tender okra", type: "Vegetable", price: "Rs 50/kg", stock: "620 kg available", imageKey: "okra" },
  { key: "red-okra", query: "red okra", type: "Vegetable", price: "Rs 72/kg", stock: "340 kg available", imageKey: "okra" },
  { key: "ridge-gourd", query: "ridge gourd", type: "Vegetable", price: "Rs 36/kg", stock: "740 kg available", imageKey: "cucumber" },
  { key: "zucchini", query: "zucchini", type: "Vegetable", price: "Rs 64/kg", stock: "580 kg available", imageKey: "cucumber" },
  { key: "green-beans", query: "green beans", type: "Vegetable", price: "Rs 58/kg", stock: "690 kg available", imageKey: "okra" },
  { key: "french-beans", query: "french beans", type: "Vegetable", price: "Rs 72/kg", stock: "520 kg available", imageKey: "okra" },
  { key: "cluster-beans", query: "cluster beans", type: "Vegetable", price: "Rs 66/kg", stock: "470 kg available", imageKey: "okra" },

  { key: "green-apple", query: "green apple", type: "Fruit", price: "Rs 135/kg", stock: "840 kg available", imageKey: "apple" },
  { key: "fuji-apple", query: "fuji apple", type: "Fruit", price: "Rs 155/kg", stock: "620 kg available", imageKey: "apple" },
  { key: "gala-apple", query: "gala apple", type: "Fruit", price: "Rs 145/kg", stock: "690 kg available", imageKey: "apple" },
  { key: "red-delicious-apple", query: "red delicious apple", type: "Fruit", price: "Rs 150/kg", stock: "760 kg available", imageKey: "apple" },
  { key: "golden-apple", query: "golden apple", type: "Fruit", price: "Rs 142/kg", stock: "540 kg available", imageKey: "apple" },
  { key: "granny-smith-apple", query: "granny smith apple", type: "Fruit", price: "Rs 160/kg", stock: "430 kg available", imageKey: "apple" },
  { key: "honeycrisp-apple", query: "honeycrisp apple", type: "Fruit", price: "Rs 210/kg", stock: "310 kg available", imageKey: "apple" },
  { key: "pink-lady-apple", query: "pink lady apple", type: "Fruit", price: "Rs 190/kg", stock: "380 kg available", imageKey: "apple" },
  { key: "royal-gala-apple", query: "royal gala apple", type: "Fruit", price: "Rs 148/kg", stock: "720 kg available", imageKey: "apple" },
  { key: "kashmiri-apple", query: "kashmiri apple", type: "Fruit", price: "Rs 138/kg", stock: "1 t available", imageKey: "apple" },
  { key: "ambri-apple", query: "ambri apple", type: "Fruit", price: "Rs 175/kg", stock: "290 kg available", imageKey: "apple" },
  { key: "washington-apple", query: "washington apple", type: "Fruit", price: "Rs 165/kg", stock: "680 kg available", imageKey: "apple" },
  { key: "robusta-banana", query: "robusta banana", type: "Fruit", price: "Rs 48/dozen", stock: "2,600 dozen", imageKey: "banana" },
  { key: "cavendish-banana", query: "cavendish banana", type: "Fruit", price: "Rs 52/dozen", stock: "2,200 dozen", imageKey: "banana" },
  { key: "elaichi-banana", query: "elaichi banana", type: "Fruit", price: "Rs 72/dozen", stock: "1,500 dozen", imageKey: "banana" },
  { key: "nendran-banana", query: "nendran banana", type: "Fruit", price: "Rs 68/dozen", stock: "1,100 dozen", imageKey: "banana" },
  { key: "red-banana", query: "red banana", type: "Fruit", price: "Rs 82/dozen", stock: "720 dozen", imageKey: "banana" },
  { key: "hill-banana", query: "hill banana", type: "Fruit", price: "Rs 78/dozen", stock: "640 dozen", imageKey: "banana" },
  { key: "yelakki-banana", query: "yelakki banana", type: "Fruit", price: "Rs 74/dozen", stock: "980 dozen", imageKey: "banana" },
  { key: "plantain", query: "plantain", type: "Fruit", price: "Rs 42/dozen", stock: "1,800 dozen", imageKey: "banana" },
  { key: "baby-banana", query: "baby banana", type: "Fruit", price: "Rs 64/dozen", stock: "1,200 dozen", imageKey: "banana" },
  { key: "poovan-banana", query: "poovan banana", type: "Fruit", price: "Rs 56/dozen", stock: "1,350 dozen", imageKey: "banana" },
  { key: "monthan-banana", query: "monthan banana", type: "Fruit", price: "Rs 50/dozen", stock: "910 dozen", imageKey: "banana" },
  { key: "raw-banana", query: "raw banana", type: "Fruit", price: "Rs 38/dozen", stock: "1,700 dozen", imageKey: "banana" },
  { key: "alphonso-mango", query: "alphonso mango", type: "Fruit", price: "Rs 220/kg", stock: "520 kg available", imageKey: "mango" },
  { key: "kesar-mango", query: "kesar mango", type: "Fruit", price: "Rs 180/kg", stock: "710 kg available", imageKey: "mango" },
  { key: "dasheri-mango", query: "dasheri mango", type: "Fruit", price: "Rs 120/kg", stock: "1.1 t available", imageKey: "mango" },
  { key: "langra-mango", query: "langra mango", type: "Fruit", price: "Rs 125/kg", stock: "920 kg available", imageKey: "mango" },
  { key: "banganapalli-mango", query: "banganapalli mango", type: "Fruit", price: "Rs 115/kg", stock: "1.4 t available", imageKey: "mango" },
  { key: "totapuri-mango", query: "totapuri mango", type: "Fruit", price: "Rs 88/kg", stock: "1.8 t available", imageKey: "mango" },
  { key: "himsagar-mango", query: "himsagar mango", type: "Fruit", price: "Rs 160/kg", stock: "480 kg available", imageKey: "mango" },
  { key: "chaunsa-mango", query: "chaunsa mango", type: "Fruit", price: "Rs 170/kg", stock: "390 kg available", imageKey: "mango" },
  { key: "malgova-mango", query: "malgova mango", type: "Fruit", price: "Rs 130/kg", stock: "670 kg available", imageKey: "mango" },
  { key: "raw-mango", query: "raw mango", type: "Fruit", price: "Rs 70/kg", stock: "1.2 t available", imageKey: "mango" },
  { key: "sindhura-mango", query: "sindhura mango", type: "Fruit", price: "Rs 105/kg", stock: "840 kg available", imageKey: "mango" },
  { key: "badami-mango", query: "badami mango", type: "Fruit", price: "Rs 140/kg", stock: "760 kg available", imageKey: "mango" },
  { key: "neelam-mango", query: "neelam mango", type: "Fruit", price: "Rs 95/kg", stock: "960 kg available", imageKey: "mango" },
  { key: "pairi-mango", query: "pairi mango", type: "Fruit", price: "Rs 118/kg", stock: "540 kg available", imageKey: "mango" },
  { key: "green-grapes", query: "green grapes", type: "Fruit", price: "Rs 82/kg", stock: "980 kg available", imageKey: "grapes" },
  { key: "black-grapes", query: "black grapes", type: "Fruit", price: "Rs 88/kg", stock: "760 kg available", imageKey: "grapes" },
  { key: "red-grapes", query: "red grapes", type: "Fruit", price: "Rs 84/kg", stock: "850 kg available", imageKey: "grapes" },
  { key: "seedless-grapes", query: "seedless grapes", type: "Fruit", price: "Rs 96/kg", stock: "720 kg available", imageKey: "grapes" },
  { key: "thompson-grapes", query: "thompson grapes", type: "Fruit", price: "Rs 92/kg", stock: "640 kg available", imageKey: "grapes" },
  { key: "crimson-grapes", query: "crimson grapes", type: "Fruit", price: "Rs 102/kg", stock: "520 kg available", imageKey: "grapes" },
  { key: "globe-grapes", query: "globe grapes", type: "Fruit", price: "Rs 110/kg", stock: "430 kg available", imageKey: "grapes" },
  { key: "muscat-grapes", query: "muscat grapes", type: "Fruit", price: "Rs 125/kg", stock: "360 kg available", imageKey: "grapes" },
  { key: "sultana-grapes", query: "sultana grapes", type: "Fruit", price: "Rs 98/kg", stock: "610 kg available", imageKey: "grapes" },
  { key: "concord-grapes", query: "concord grapes", type: "Fruit", price: "Rs 118/kg", stock: "390 kg available", imageKey: "grapes" },
  { key: "sharad-grapes", query: "sharad grapes", type: "Fruit", price: "Rs 106/kg", stock: "570 kg available", imageKey: "grapes" },
  { key: "flame-grapes", query: "flame grapes", type: "Fruit", price: "Rs 104/kg", stock: "490 kg available", imageKey: "grapes" },
];
